### PR TITLE
Suggestions 🎉

### PR DESCRIPTION
**Pull request by sunny**
When enabling `suggestions: true` in the Pronto YML configuration under `rubocop:`,  messages will include a line suggesting what to change, using [GitHub's](https://twitter.com/wa7son/status/1052326282900443137) new syntax on Pull Request reviews.

For example, for this change:

```diff
  end
+
+def do_something
+  "bar"
+end
end
```

The message will have a suggestion in this format:

````
Prefer single-quoted strings when you don't need string interpolation
or special symbols.

```suggestion
  'bar'
```
````

Which appears as GitHub comments like this:

GitHub screenshot with suggestion

That can be applied in one click right from the Pull Request.

### CODE REVIEW

**Comment by mmozuras** [comment]
@sunny looks good. Could you rebase this PR on top of current master?

**Comment by sunny** [comment]
Hey @mmozuras, thanks for looking into this!  I rebased against master.

I am using the `RUBOCOP_SUGGESTION_COPS` ENV var in my CI and for my use-case, this PR works fine and could be merged as-is.

However, I am not convinced that using an environment variable is the best way to store this configuration going forward.

Would you have any suggestions as to where to hold this configuration?

I am considering:

- An option in `.pronto.yml`, e.g.

  ```
  rubocop:
    suggestion_cops:
  ```

- Having it as a "variable" inside the GitHub formatter in `.pronto.yml`

  ```yml
  github_pr:
    format: "%{runner} - %{msg}\n%{suggestion}"
  ```

- Configuration inside `rubocop.yml`
  => that would require to do modifications inside RuboCop itself
- Or, perhaps, having a single "show suggestions" setting and using another heuristic to determine whether this is a cop that works well as a suggestion (did it only touch one line, for example).

**Comment by mmozuras** [comment]
@sunny I like the idea of putting it somewhere/somehow in `.pronto.yml`. The first option you've suggested looks good. I think that the solution could  also be generalized for each Pronto runner to have access to it.

**Comment by doomspork** [comment]
Howdy @sunny and @mmozuras! I like the cleanliness of Option 1 👌 

@prontolabs/core any additional thoughts?

**Comment by aergonaut** [comment]
I believe GitHub suggestions only work with single-line diffs. What would happen if the RuboCop suggestion is longer than 1 line? Maybe there should be a check to make sure that only 1-line corrections get turned into suggestions, and other corrections just get included as code blocks?

**Comment by sunny** [comment]
> Maybe there should be a check to make sure that only 1-line corrections get turned into suggestions, and other corrections just get included as code blocks?

That would be awesome, we wouldn't need to keep a list at all that way.

However I didn't manage to get it working that way since calling all cops with autocorrect could change the lines of the next suggestions. Maybe I need to continue digging to find a good solution.

**Comment by sunny** [comment]
@aergonaut @doomspork @mmozuras I figured out how to have only suggestions of cops that moved one line at a time. This means we don't need an environment variable that lists all cops. \o/

I just kept one environment variable to activate or not this feature.

What do you think?

**Comment by doomspork** [comment]
@sunny sorry for the delay, that single option sounds ideal 👍 

I'll review your PR and add the @prontolabs/core team as well for a final review.

**Comment by sunny** [comment]
Any chance for a final review here? 🙏

**Comment by doomspork** [comment]
@sunny sorry for the delays, could you rebase so I can merge?

**Comment by sunny** [comment]
@doomspork Rebased! I fixed a few conflicts over the new configuration for severity.

**Comment by sunny** [comment]
Woohoo! \o/ Thanks for the review and the merge. 🎉

**Pull request merged**
