### PR TITLE
Update Rubocop to 0.51

### PR DESCRIPTION
**Pull request by cayter**

### CODE REVIEW

**Comment by doomspork** [comment]
@prontolabs/core are we open to dropping support for Ruby 2.0?

**Comment by cayter** [comment]
Didn't know Rubocop 0.51 isn't compatible with Ruby 2.0. But it's really annoying that pronto-rubocop is so outdated.

**Comment by doomspork** [comment]
@cayter are we missing a significant feature?  We have to weigh the pros and cons of upgrading libraries to the new-new at the expense of limiting the number of people who can use Pronoto due to language limitations.

We always open to suggestions if a case can be made for breaking changes 👍

**Comment by mknapik** [comment]
I believe it would be best to leave it up to pronto users what version of RuboCop they wish to use. (as long as API is compatible)
@cayter Is there any issue with having the following contents in a Gemfile:

```ruby
gem 'pronto'
gem 'rubocop', '~> 0.51'
```

**Comment by cayter** [comment]
@doomspork @mknapik Thanks for taking ur time but I guess we can enforce the rubocop version in Gemfile, so it is not a big deal. Again, thanks.

**Comment by mknapik** [comment]
Since RuboCop tends to introduce new violations with each version leaving up to the user which version should be used is more flexible.

**Pull request closed without merging**
