### PR TITLE
28: Allow auto-correct

### PR DESCRIPTION
**Pull request by dorner**
See #28.

### CODE REVIEW

**Comment by gorkunov** [comment]
@mmozuras Is there anything that blocks merging this?

**Comment by drewpterry** [comment]
By the way I think this will run autocorrect over the entire file, not just the changed lines which I don't think is the expected result.

**Comment by dorner** [comment]
Yep, it will autocorrect the whole file - unfortunately there's no easy way to fix that. Still, for most repos I think they'd be fine with it (I know in my case, working with a large legacy app, I quite appreciate it).

**Comment by doomspork** [comment]
I'm not for merging this change because the use-case for this is very small.  I believe most people using Pronto are doing so with CD/CI services where this autocorrect functionality wouldn't work.

If you're looking to have your code fixed up for you you could simplify run Rubocop outside of Pronto without modifying Pronto's internal workings.

**Comment by gorkunov** [comment]
could we add command line flag instead of global configuration file? That should fix problem with CI and in the same time allow auto-fix issues locally. I do like idea run only pronto locally for checking/fixing instead of running both pronto and then rubocop for fixing b/c it looks ugly.

**Comment by supremebeing7** [comment]
I also would like to see this happen, but with `gorkunov`'s suggestion of running with a flag. This would support my team's ideal workflow:
1. Run pronto locally during development with `--autocorrect` on
2. Fix any non-autocorrectable offenses manually
3. Push to CI where it runs pronto without `--autocorrect` to ensure all offenses are fixed

**Comment by mknapik** [comment]
I'd like to understand an advantage of using auto correction with pronto instead of using `rubocop -a`. Is it useful for projects which maintains consistent style only in the subset of a project code?

**Comment by supremebeing7** [comment]
In my previous rubocop autocorrect experiences, there were two issues:
- it has incorrectly autocorrected code, so running it on a subset of project code is easier to verify that the autocorrect changes made are right; and
- autocorrecting the entire repo, for a large repo, would need to be done separately if there are a lot of corrections, otherwise it would drown out the rest of the code.

I suppose a solution that is reasonable would just be to run autocorrect on the whole repo as a separate PR first, then the first bullet above becomes less of an issue.

**Comment by mknapik** [comment]
@supremebeing7 
* It's interesting that you had such a problem. I remember we run into an issue while having 2 ruby versions for a single app and running Rubocop with only one version. Other than that, we never run into any issues.
* That's exactly the way we dealt with styling conventions on the last big project I worked on. Once we agreed on common conventions Rubocop autocorrect was used for the whole project. It was a team conscious decision though. However, I see little to no disadvantages of such approach.

**Comment by mmozuras** [comment]
I agree with @doomspork. I'd like to keep Pronto read-only and not expand its feature in this way.

**Comment by supremebeing7** [comment]
FWIW, I know this is a few years old but my current team has been using [pre-commit](https://github.com/pre-commit/pre-commit) with `rubocop -a` to achieve basically the goal of this PR -- works pretty well. 

Pronto is still a great option for CI/read-only.

**Comment by richkettle** [comment]
My use case for this feature is a legacy application that has probably 100k offences. Rather than changing every single one of the of the files in the codebase we are making sure that new stuff is conforming while at the same time gradually moving towards having the entire codebase compliant.

Having this on diffs per commit is what we are looking for. We do have it running through CI but automating the easier parts of this is going to help me out a huge amount. I don't know of a way of doing this through just rubocop i.e. without ponto. I'd welcome any suggestions.

**Comment by crokobit** [comment]
Need this to work with legacy code locally. 😢

**Pull request closed without merging**
