### PR TITLE
Allow Gemfile.local for development purposes

### PR DESCRIPTION
**Pull request by marcandre**

### CODE REVIEW

**Comment by ashkulz** [comment]
@marcandre is this still required? If so, I'd appreciate a merge/rebase on top of `master`.

**Comment by marcandre** [comment]
It's not required, but it's still a good idea.

There is no conflict.

**Comment by ashkulz** [comment]
@marcandre: I've not needed to use it before, can you describe why/what you'd put inside `Gemfile.local`?

**Comment by marcandre** [comment]
> @marcandre: I've not needed to use it before, can you describe why/what you'd put inside `Gemfile.local`?

```ruby
gem 'rubocop', path: '../rubocop'
```

**Pull request merged**
