### PR TITLE
Update Rubocop & test 2.7

### PR DESCRIPTION
**Pull request by marcandre**
Combines #54 and #55, to see if Travis will kick in

### CODE REVIEW

**Comment by ashkulz** [comment]
@marcandre this still fails on Ruby 2.3? Also, I'd be more comfortable that we used something like [`appraisal`](https://github.com/thoughtbot/appraisal) to ensure that we actually run tests with two different RuboCop versions, rather than assuming it works.

**Comment by marcandre** [comment]
> @marcandre this still fails on Ruby 2.3?

Oh, right, I see this. Fixing now, sorry.

> Also, I'd be more comfortable that we used something like [`appraisal`](https://github.com/thoughtbot/appraisal) to ensure that we actually run tests with two different RuboCop versions, rather than assuming it works.

Do what you want, but if you look at the log and expand the `bundle install` segment, you'll see that rubocop 0.81 is installed. There is no way that newer rubocop will ever be compatible with Ruby 2.3; we'll probably drop 2.4 early next year.

**Comment by marcandre** [comment]
Green in 2.3

**Comment by ashkulz** [comment]
Thanks, @marcandre!

**Comment by knappe** [comment]
@ashkulz Any chance we could get a release of this with the updated rubocop dependency changes? 😄

**Comment by ashkulz** [comment]
I think I can create a tag, but I don't have permissions to make a release to RubyGems (I was recently invited to the org). Not sure who has that, probably @mmozuras or @doomspork?

**Comment by ashkulz** [comment]
I changed the dependency to be `< 1.0`, see 5dfe984763b88bfb23f91d4982d69be213a9fa1b -- there were failing tests and fixing them wasn't easy. I'll do a followup release sometime.

**Comment by marcandre** [comment]
I'll have a look tomorrow

**Comment by marcandre** [comment]
So there are two issues.
One is caused by [a bug in RuboCop](https://github.com/rubocop-hq/rubocop/issues/9482) which you can temporarily bypass by changing `s.required_ruby_version = '>= 2.3.0'` to `'>= 2.4.0'` in the gemspec.

The other is that `spec/pronto/rubocop/patch_cop_spec.rb` no longer passes. I hope I won't offend anyone by stating that this spec file is simply horrible. It uses no less than 7 spec doubles for RuboCop's internals, and even worse patches 3 RuboCop methods unilaterally to return those doubles.

The internals have changed, the config loading code calls one of these 3 methods for another purpose and 💣 .

The solution is to send this spec file to `/dev/null` and do without or rewrite it properly. I'm afraid I have no inclination to help further in that regards.

**Comment by ashkulz** [comment]
Thanks, @marcandre! I became a maintainer _very_ recently, so I'm not familiar with this part of the code.

I'll take a look at it this weekend and release `0.11.1` which is compatible with RuboCop >= 1.0 🤞

**Comment by thatguysimon** [comment]
Hey @ashkulz! Any luck with this?

**Comment by ashkulz** [comment]
@thatguysimon, @eitoball did make an attempt in #60, but I personally haven't had time to action it myself yet :slightly_frowning_face:

**Pull request merged**
