### PR TITLE
26: Configure severity via config file

### PR DESCRIPTION
**Pull request by dorner**
See #26.

### CODE REVIEW

**Comment by mknapik** [comment]
@mmozuras Personally I find this feature quite useful. I can take care of testing if we're willing to merge it.

**Comment by mmozuras** [comment]
@mknapik sure, add tests and let's merge this one 🙂.

**Comment by adamolien** [comment]
@mmozuras @mknapik Any updates on what happened to this PR? I recently came across the issue in my project. If it needs any help let me know and I can try to help out.

**Comment by mknapik** [comment]
@adamolien The structure of the gem changed so we would have to update the way feature is configured. I managed to resolve conflicts (with a little bit of refactoring).
If you would be willing to add some tests and test this version in your project. I could merge it to master.

**Comment by adamolien** [comment]
@mknapik I added a few new tests. I am new to rspec though so please let me know if you want anything changed!

I am also a bit new to open source contributions, should I create a PR into this branch? Or what is the best way to get the code merged in?

**Comment by mknapik** [comment]
@adamolien Good question, I believe only members can push code to someone else PRs.
Feel free to create a new PR containing all commits from this PR with your code on top.

**Comment by doomspork** [comment]
Feature added via #44

**Pull request closed without merging**
